---
branches:
  - main
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - ["@saithodev/semantic-release-gitea", {
    "giteaUrl": 'https://gitea.degert-it.de',
    "assets": [
      {"path": "CHANGELOG.md"}
    ]
  }]
