name: ansible-lint
on: [push] # noqa yaml[truthy]
jobs:
  ansible_lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    container:
      image: ansible-lint-runner:1.1
    steps:
      - uses: actions/checkout@v4
      - name: Run ansible-lint
        run: ansible-lint -v
