name: semantic-release
on: [push] # noqa yaml[truthy]
jobs:
  ansible_lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    container:
      image: ansible-lint-runner:1.1
    steps:
      - uses: actions/checkout@v4
      - name: Run ansible-lint
        run: ansible-lint -v
  release:
    name: release
    runs-on: ubuntu-latest
    needs: ansible_lint
    if:
      contains('refs/heads/main', github.ref)
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            @saithodev/semantic-release-gitea
        env:
          GITEA_TOKEN: ${{ secrets.GITEA_TOKEN }}
